/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A cooperative cancellation handle bridged from a JavaScript `AbortSignal`. */
export declare class Cancellation {
  constructor()
  cancel(): void
  get cancelled(): boolean
}

/** An opened or freshly built persistent content index. */
export declare class NativeIndex {
  /** Opens a saved index without rescanning any repository. */
  static open(path: string, optionsJson?: string | undefined | null): NativeIndex
  /** Builds a complete index on the calling thread. */
  static buildSync(rootsJson: string, optionsJson?: string | undefined | null, savePath?: string | undefined | null, cancellation?: Cancellation | undefined | null): NativeIndex
  get fileCount(): number
  get revision(): string
  /** Returns the cheap health status of the resident snapshot. */
  statusJson(): string
  /** Returns the build report when this handle came from a build. */
  buildReportJson(): string | null
  /** Saves the resident snapshot atomically. */
  save(path: string): void
  searchJson(queryJson: string, optionsJson?: string | undefined | null): Promise<unknown>
  searchJsonSync(queryJson: string, optionsJson?: string | undefined | null): string
  /** Applies watcher events for one root and returns the update report. */
  updateEventsJson(rootIndex: number, eventsJson: string, optionsJson?: string | undefined | null): string
  /** Rescans every indexed root and replaces the snapshot in place. */
  rebuildJson(optionsJson?: string | undefined | null): string
}

/** Builds a complete index off the JavaScript event loop. */
export declare function buildIndex(rootsJson: string, optionsJson?: string | undefined | null, savePath?: string | undefined | null, cancellation?: Cancellation | undefined | null): Promise<unknown>

export declare function searchRepositories(rootsJson: string, queryJson: string, optionsJson?: string | undefined | null, cancellation?: Cancellation | undefined | null): Promise<unknown>

export declare function searchRepositoriesSync(rootsJson: string, queryJson: string, optionsJson?: string | undefined | null, cancellation?: Cancellation | undefined | null): string
